import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";

const GHL_API = "https://services.leadconnectorhq.com";
const GHL_KEY = process.env.GHL_API_KEY || "";
const GHL_LOC = process.env.GHL_LOCATION_ID || "";

// GHL Pipeline IDs
const ONBOARDING_PIPELINE = "R6G5m2bF6vxtoho9ZeQH";
const ONBOARDING_STAGES = {
  agreement: "b18bc20f-5f93-499e-a3a6-e89dc793f00c",
  paid: "3a073acd-3d6f-4d65-b41f-1f8a4c5cc040",
  onboarding_scheduled: "c56da4e2-28f4-4f24-82c2-e4b36c7e6e35",
  intake_form: "4d4c4dbd-7e64-4f0e-aabf-ec63b7d56d70",
  onboarded: "c06bd721-e4e2-4a12-9f08-7e3a7f1c2c3e",
};

const JARVIS_HOOK = "http://172.26.0.5:18790/hooks/agent";
const FLEET_TOKEN = "fleet_ops_2026";

const DATA_DIR = "/workspace/agents/elon";
const ONBOARDING_FILE = `${DATA_DIR}/onboarding-clients.json`;

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

// Fulfillment file - direct write (no self-HTTP)
const FULFILLMENT_FILE = join(process.cwd(), "data", "fulfillment.json");
function loadFulfillment(): any[] {
  try { if (existsSync(FULFILLMENT_FILE)) return JSON.parse(readFileSync(FULFILLMENT_FILE, "utf-8")); } catch {}
  return [];
}
function createFulfillmentRecord(data: any): any {
  const dir = join(process.cwd(), "data");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const records = loadFulfillment();
  const record = { id: `f_${Date.now()}`, ...data, createdAt: new Date().toISOString(), stage: "onboarding", tasks: [] };
  records.unshift(record);
  writeFileSync(FULFILLMENT_FILE, JSON.stringify(records, null, 2));
  return record;
}

function loadClients(): any[] {
  try {
    if (existsSync(ONBOARDING_FILE)) return JSON.parse(readFileSync(ONBOARDING_FILE, "utf-8"));
  } catch {}
  return [];
}
function saveClients(data: any[]) {
  try {
    if (!existsSync(DATA_DIR)) mkdirSync(DATA_DIR, { recursive: true });
    writeFileSync(ONBOARDING_FILE, JSON.stringify(data, null, 2));
  } catch {}
}

function buildBrief(form: any): string {
  return `
NEW CLIENT ONBOARDED — ${form.businessName}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Contact: ${form.contactName} (${form.phone || "no phone"})
Email: ${form.email}
Niche: ${form.niche} | Tier: ${form.tier}
City: ${form.city || "Unknown"}

Business: ${form.businessName}
Website (current): ${form.currentWebsite || "None"}
Goal: ${form.primaryGoal || "Not specified"}

Pain points: ${form.painPoints || "Not specified"}
Monthly budget: ₹${form.budget || "Not discussed"}
Timeline expectation: ${form.timeline || "ASAP"}

Special notes: ${form.notes || "None"}

NEXT STEPS:
1. Send Agreement (Day 0)
2. Collect payment — ₹${form.tier === "Starter" ? "15,000" : form.tier === "Growth" ? "25,000" : "40,000"}/mo
3. Schedule onboarding call within 48h
4. Build & deliver within ${form.tier === "Starter" ? "5" : form.tier === "Growth" ? "7" : "10"} days

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[AUTO-GENERATED by MC Onboarding Engine]
`.trim();
}

export async function GET(): Promise<any> {
  const clients = loadClients();
  return NextResponse.json({ clients, total: clients.length });
}

export async function POST(req: NextRequest): Promise<any> {
  try {
    const body = await req.json();
    const { action } = body;

    // ─── ONBOARD: full cascade trigger ───
    if (action === "onboard") {
      const form = body.form as Record<string, string>;
      if (!form.contactName || !form.email || !form.niche || !form.businessName) {
        return NextResponse.json({ error: "Required: contactName, email, niche, businessName" }, { status: 400 });
      }

      const results: Record<string, any> = {};
      const errors: string[] = [];

      // ── Step 1: Create GHL Contact ──
      try {
        const ghlPayload: any = {
          firstName: form.contactName.split(" ")[0],
          lastName: form.contactName.split(" ").slice(1).join(" ") || "",
          email: form.email,
          phone: form.phone || "",
          address1: form.city || "",
          source: "MC Onboarding Engine",
          tags: [form.niche, form.tier || "Starter", "mc-onboard"],
          locationId: GHL_LOC,
        };

        const ghlRes = await fetch(`${GHL_API}/contacts/`, {
          method: "POST",
          headers: { Authorization: `Bearer ${GHL_KEY}`, "Content-Type": "application/json", Version: "2021-07-28" },
          body: JSON.stringify(ghlPayload),
        });
        const ghlData = await ghlRes.json();
        if (ghlData.contact?.id) {
          results.ghlContactId = ghlData.contact.id;
          results.ghlContactName = ghlData.contact.contactName;

          // ── Step 2: Move GHL Contact to Onboarding Pipeline (Agreement stage) ──
          try {
            const oppRes = await fetch(`${GHL_API}/opportunities/`, {
              method: "POST",
              headers: { Authorization: `Bearer ${GHL_KEY}`, "Content-Type": "application/json", Version: "2021-07-28" },
              body: JSON.stringify({
                pipelineId: ONBOARDING_PIPELINE,
                pipelineStageId: ONBOARDING_STAGES.agreement,
                title: `${form.businessName} — ${form.tier || "Starter"}`,
                contactId: ghlData.contact.id,
                monetaryValue: form.tier === "Starter" ? 15000 : form.tier === "Growth" ? 25000 : 40000,
                status: "open",
                locationId: GHL_LOC,
              }),
            });
            const oppData = await oppRes.json();
            results.ghlOpportunityId = oppData.opportunity?.id;
            results.ghlPipelineStage = "Agreement";
          } catch (e: any) {
            errors.push(`GHL pipeline: ${e.message}`);
          }
        } else {
          errors.push(`GHL contact: ${JSON.stringify(ghlData).slice(0, 100)}`);
        }
      } catch (e: any) {
        errors.push(`GHL: ${e.message}`);
      }

      // ── Step 3: Create Fulfillment Record (direct write, no HTTP self-call) ──
      try {
        const record = createFulfillmentRecord({
          clientName: form.businessName,
          contactName: form.contactName,
          niche: form.niche,
          tier: form.tier || "Starter",
          city: form.city || "",
          email: form.email,
          phone: form.phone || "",
          startDate: new Date().toISOString(),
          ghlContactId: results.ghlContactId || "",
        });
        results.fulfillmentId = record.id;
      } catch (e: any) {
        errors.push(`Fulfillment: ${e.message}`);
      }

      // ── Step 4: Notify Jarvis with personalized brief ──
      const brief = buildBrief(form);
      try {
        const hookRes = await fetch(JARVIS_HOOK, {
          method: "POST",
          headers: { Authorization: `Bearer ${FLEET_TOKEN}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            message: `FROM_ELON: New client onboarded via MC. Prepare welcome sequence.\n\n${brief}`,
          }),
          signal: AbortSignal.timeout(5000),
        });
        results.jarvisNotified = hookRes.ok;
      } catch {
        results.jarvisNotified = false;
        errors.push("Jarvis hook timeout (non-critical)");
      }

      // ── Step 5: Save record locally ──
      const record = {
        id: `onboard_${Date.now()}`,
        ...form,
        tier: form.tier || "Starter",
        createdAt: new Date().toISOString(),
        ghlContactId: results.ghlContactId,
        ghlOpportunityId: results.ghlOpportunityId,
        fulfillmentId: results.fulfillmentId,
        status: "agreement-sent",
        brief,
      };
      const clients = loadClients();
      clients.unshift(record);
      saveClients(clients);
      results.localRecordId = record.id;

      return NextResponse.json({
        success: true,
        results,
        errors,
        brief,
        clientName: form.businessName,
        message: `${form.businessName} onboarded! GHL contact ${results.ghlContactId ? "✓" : "✗"} · Pipeline ${results.ghlOpportunityId ? "✓" : "✗"} · Fulfillment ${results.fulfillmentId ? "✓" : "✗"} · Jarvis ${results.jarvisNotified ? "✓" : "✗"}`,
      });
    }

    return NextResponse.json({ error: "Unknown action" }, { status: 400 });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
